### ISSUE TITLE
Cant find active or waiting channel ids in dashboard

### ISSUE THREAD

**Issue by Prajjwal-Arya** [gauravagarwaltal/Shipment#1]
After adding users and opening channels, I cant find any active or waiting channel ids in dashboard.

**Comment by gauravagarwaltal** [comment]
I checked again. It is working, you need to click on "Apply filter Event" to update changes happened on the contract-side.
I am closing this issue. Reopen it if you face this problem again.
<img width="806" alt="Screenshot 2020-06-11 at 9 00 41 AM" src="https://user-images.githubusercontent.com/52406920/84341966-0a1e8980-abc2-11ea-9a05-7b8d8e4fcda4.png">
